spring:
  application:
    name: movie-consumer-feign-customizing
server:
  port: 7911
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
#设置调用UserFeignClient时日志的打印方式
logging:
  level:
    com.alan.cloud.feign.UserFeignClient: DEBUG
# 解决第一次请求报超时异常的方案：
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
# 或者：
# hystrix.command.default.execution.timeout.enabled: false
# 或者：
## 索性禁用feign的hystrix支持
feign.hystrix.enabled: false

# 超时的issue：https://github.com/spring-cloud/spring-cloud-netflix/issues/768
# 超时的解决方案： http://stackoverflow.com/questions/27375557/hystrix-command-fails-with-timed-out-and-no-fallback-available
# hystrix配置： https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds