server:
  port: 8762
eureka:
  instance:
    hostname: server2
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@server2:8761/eureka,http://root:root@server3:8763/eureka