server:
  port: 8763
eureka:
  instance:
    hostname: server3
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@server1:8761/eureka,http://root:root@server2:8762/eureka