spring:
  application:
    name: movie-consumer-ribbon-customizing
server:
  port: 8011
eureka:
  client:
    instance:
      prerer-ip-address: true
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
#定义微服务user-provider负载均衡策略，如有多个微服务，则其他的微服务遵循轮循策略
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule