spring:
  application:
    name: movie-consumer-feign
server:
  port: 7910
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
#feign:
#  httpclient:
#    enabled: true