spring:
  application:
    name: movie-consumer
server:
  port: 7901
#直接关联获取user-provider信息
user:
  userServicePath: http://localhost:7900/simple/
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true